spring:
    datasource:
       url: jdbc:oracle:thin:@//10.51.119.112:1521/XE
       username: ARNOL  
       password: choche       
       driver-class-name: oracle.jdbc.OracleDriver
    jpa:
        database: default
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
              strategy: org.hibernate.cfg.ImprovedNamingStrategy        
        
        
    thymeleaf:
       cache: false
server:
    port: 9093
    
bar:
  datasource:
    url: jdbc:mysql://localhost/bar_schema
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
    
   
    